meta_product_name: "Placeholder"
meta_title: "Placeholder - Placeholder - Capture the best moments with your loved ones, even if you are apart"
meta_description: "Placeholder is a social and photo app using Augmented Reality."
meta_image: "placeholder_meta.png"
